services:
  # super-app:
  #   build: .
  #   ports:
  #     - '5000:3000'
  #   depends_on:
  #     - postgres
  #   networks:
  #     - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    networks:
      - postgres

  redis:
    image: redis
    ports:
      - '6379:6379'
networks:
  postgres:
    driver: bridge
